/*
 * generated by Xtext 2.9.1
 */
package org.casualintellect.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class CasualIntellectWebModule extends AbstractCasualIntellectWebModule {
}
