/*
 * generated by Xtext 2.9.1
 */
package org.casualintellect.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.name.Names;
import java.util.concurrent.ExecutorService;
import org.casualintellect.ide.contentassist.antlr.CasualIntellectParser;
import org.casualintellect.ide.contentassist.antlr.internal.InternalCasualIntellectLexer;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.ide.editor.contentassist.antlr.IContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link CasualIntellectWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractCasualIntellectWebModule extends DefaultWebModule {

	public AbstractCasualIntellectWebModule(Provider<ExecutorService> executorServiceProvider) {
		super(executorServiceProvider);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public void configureContentAssistLexer(Binder binder) {
		binder.bind(Lexer.class).annotatedWith(Names.named(LexerIdeBindings.CONTENT_ASSIST)).to(InternalCasualIntellectLexer.class);
	}
	
	// contributed by org.eclipse.xtext.xtext.generator.web.WebIntegrationFragment
	public Class<? extends IContentAssistParser> bindIContentAssistParser() {
		return CasualIntellectParser.class;
	}
	
}
