/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.web;

import com.google.inject.Provider;
import java.util.concurrent.ExecutorService;
import org.casualintellect.web.AbstractCasualIntellectWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CasualIntellectWebModule extends AbstractCasualIntellectWebModule {
  public CasualIntellectWebModule(final Provider<ExecutorService> executorServiceProvider) {
    super(executorServiceProvider);
  }
}
