/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import org.casualintellect.CasualIntellectRuntimeModule;
import org.casualintellect.CasualIntellectStandaloneSetup;
import org.casualintellect.web.CasualIntellectWebModule;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CasualIntellectWebSetup extends CasualIntellectStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final CasualIntellectRuntimeModule runtimeModule = new CasualIntellectRuntimeModule();
    final CasualIntellectWebModule webModule = new CasualIntellectWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public CasualIntellectWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
