/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.ui;

import org.casualintellect.ui.AbstractCasualIntellectUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class CasualIntellectUiModule extends AbstractCasualIntellectUiModule {
  public CasualIntellectUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
