/**
 * generated by Xtext 2.9.1
 */
package org.casualintellect.ui.contentassist;

import org.casualintellect.ui.contentassist.AbstractCasualIntellectProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class CasualIntellectProposalProvider extends AbstractCasualIntellectProposalProvider {
}
